"""Domain and API models for LLM recommendations and responses."""

from typing import List, Optional
from pydantic import BaseModel, Field

from src.models.preferences import UserPreferences
from src.models.restaurant import Restaurant


class GeminiRecommendationItem(BaseModel):
    """Single restaurant recommendation item parsed from raw Gemini LLM JSON response."""

    restaurant_id: str = Field(
        ..., description="Unique restaurant ID matching an ID from the candidate set"
    )
    rank: int = Field(..., ge=1, description="Ranking position (1-indexed)")
    explanation: str = Field(
        ..., description="Personalized explanation describing why this restaurant was selected"
    )


class GeminiRawResponse(BaseModel):
    """Raw structured response schema expected from Google Gemini."""

    summary: Optional[str] = Field(
        default=None, description="Brief overview of why these recommendations fit the user"
    )
    recommendations: List[GeminiRecommendationItem] = Field(
        default_factory=list, description="Ranked list of recommended restaurant items"
    )


class RecommendationMeta(BaseModel):
    """Metadata attached to recommendation responses."""

    candidate_count: int = Field(
        ..., ge=0, description="Total number of candidates matching deterministic filters"
    )
    filters_applied: UserPreferences = Field(
        ..., description="User preferences applied during candidate filtering"
    )


class Recommendation(BaseModel):
    """Final hydrated recommendation combining AI ranking/explanation with dataset facts."""

    rank: int = Field(..., ge=1, description="Recommendation rank position")
    restaurant: Restaurant = Field(
        ..., description="Full factual restaurant details from the dataset"
    )
    explanation: str = Field(
        ..., description="AI-generated explanation tailored to user preferences"
    )


class RecommendationResponse(BaseModel):
    """Complete recommendation response payload for UI or API consumption."""

    summary: Optional[str] = Field(
        default=None, description="Overall summary generated by Gemini"
    )
    recommendations: List[Recommendation] = Field(
        default_factory=list, description="Hydrated list of ranked recommendations"
    )
    meta: Optional[RecommendationMeta] = Field(
        default=None, description="Execution metadata including candidate counts and filters"
    )
