[theme]
primaryColor = "#cb202d"
backgroundColor = "#131313"
secondaryBackgroundColor = "#1b1b1b"
textColor = "#e5e2e1"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true
